version: "3"
services:
   mrtg:
      build: .
      container_name: mrtg
      image: ggosselin/mrtg:rpi
      volumes:
        - "/data/mrtg/:/home/mrtg/data"
        - "/etc/localtime:/etc/localtime:ro"
      restart: always
