version: "3.2"
services:
  mrtg:
    build: .
    container_name: mrtg
    image: registry.snafui.com:5000/mrtg:armhf
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
     - /docker/data/config/mrtg/nodes.csv:/home/mrtg/cfg/nodes.csv:ro
     - /docker/data/volume/mrtg/:/home/mrtg/data
