version: "3.1"
services:
   mrtg:
      build: /docker/build/mrtg-rpi
      container_name: mrtg
      image: registry.snafui.com:5000/mrtg:rpi
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /docker/data/config/mrtg/nodes.csv:/home/mrtg/nodes.csv:ro
        - /docker/data/volume/mrtg/:/home/mrtg/data
